### ISSUE TITLE
SKSE DLL loading errors on startup

### ISSUE THREAD

**Issue by borish43b** [ThirdEyeSqueegee/Ro#11]
Hi,
I am not sure if this is a general issue or some version clash:
When I am starting Ro i get various "dll cannot be loaded" 0000045A errors like the one shown in the screenshot:
![grafik](https://github.com/ThirdEyeSqueegee/Ro/assets/61952043/c42ba52d-4ef9-4a9c-a4a7-9c6b6653eda3)
Skyrim and Ro are fresh installs running through without any issues. I tried to disable the mods I get other dll errors (all in the SQUEEGEE's GROW OP category) . If I ignore the error the game starts just fine but I have a bad feeling about it.

Any suggestions?

**Comment by MisterPantufa** [comment]
Hi, do you have Microsoft Visual C++ Redistributable Version, x86 and x64 versions installed? I was having this same problem, and it was happening because I didn't have this software installed.

**Comment by JGainesTX** [comment]
Interesting but the issue borish43b is having is the exact issue I was having with Licentia Black this week.  I did a clean install of Skyrim and LB twice, but the problem remained.  Been modding myself for about three years so not a newbie to any of this but I have never run into this before, And now I see it is happening with other mod packs.  Something within Wabbajack maybe?
