### ISSUE TITLE
SKSE crashes

### ISSUE THREAD

**Issue by SSFantastique** [ThirdEyeSqueegee/Ro#2]
Hello!
I've been having issues, constant crashes due to unknown reasons, I suspect V-ram isn't enough but I have no clue if that's 100% the reason, as I am using 11.5gb / 12gb on my 4070ti.

Skyrim SSE v1.6.640
CrashLoggerSSE v1-8-0-0 Feb  1 2023 00:20:05

Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF941864414 d3d11.dll+0104414	mov rax, [rsi+0x110]

SYSTEM SPECS:
	OS: Microsoft Windows 11 Pro v10.0.22621
	CPU: GenuineIntel 12th Gen Intel(R) Core(TM) i9-12900K
	GPU #1: Nvidia AD104 [GeForce RTX 4070 Ti]
	GPU #2: Intel AlderLake-S GT1
	GPU #3: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 24.21 GB/31.79 GB

PROBABLE CALL STACK:
	[ 0] 0x7FF941864414    d3d11.dll+0104414
	[ 1] 0x7FF60A32F4AB SkyrimSE.exe+0DBF4AB -> 77386+0x60B
	[ 2] 0x7FF60A32A3F8 SkyrimSE.exe+0DBA3F8 -> 77263+0x68
	[ 3] 0x7FF60A99CDB0 SkyrimSE.exe+142CDB0 -> 107637+0x430
	[ 4] 0x7FF60A99DF8C SkyrimSE.exe+142DF8C -> 107644+0x31C
	[ 5] 0x7FF60A99DB04 SkyrimSE.exe+142DB04 -> 107642+0x294 BSBatchRenderer::sub
	[ 6] 0x7FF60A95EFBE SkyrimSE.exe+13EEFBE -> 106609+0xFE  BSShaderAccumulator::sub
	[ 7] 0x7FF60A95CCF9 SkyrimSE.exe+13ECCF9 -> 106583+0x89  BSShaderAccumulator::sub
	[ 8] 0x7FF60A9530E2 SkyrimSE.exe+13E30E2 -> 106437+0x72  NiCamera::sub
	[ 9] 0x7FF60A977A94 SkyrimSE.exe+1407A94 -> 107142+0x124
	[10] 0x7FF609B5B096 SkyrimSE.exe+05EB096 -> 36559+0x846  Main::Draw
	[11] 0x7FF609B5A822 SkyrimSE.exe+05EA822 -> 36558+0x122  Main::sub
	[12] 0x7FF609B5A46D SkyrimSE.exe+05EA46D -> 36555+0x4CD  Main::sub
	[13] 0x7FF609B5CCD7 SkyrimSE.exe+05ECCD7 -> 36564+0xA97  Main::Update
	[14] 0x7FF609B54DD5 SkyrimSE.exe+05E4DD5 -> 36544+0x165
	[15] 0x7FF60A9E4C1E SkyrimSE.exe+1474C1E -> 109636+0x106
	[16] 0x7FF9466826AD KERNEL32.DLL+00126AD
	[17] 0x7FF947C2A9F8    ntdll.dll+005A9F8

If you need anything else to help me out in any way-shape or forme, I will try and provide it.
The mod-list is awesome!

**Comment by ThirdEyeSqueegee** [comment]
Join the discord server and post crash logs please
