### ISSUE TITLE
Upgrade modlist from v1.6.29 to v1.7.7 leads to savegame corruption

### ISSUE THREAD

**Issue by nicolas-r** [ThirdEyeSqueegee/Ro#3]
Hello

thanks for your modlist.

I have just upgraded it, but when I load my savegame, the game warns me that a lot of mods are missing and after the loading screen, it says that mmy savegame is corrupt.

Do you know if I can find the v1.7.0 somewhere ? To try to do some intermediate upgrades

Thanks

Nicolas

**Comment by ThirdEyeSqueegee** [comment]
A new save is required when the first or second version number changes.
